export const sheetHeaderCols = [
  'GP',
  'RGS PROVIDER',
  'GAME NAME',
  'RGS code 1',
  'RGS code 2',
  'ModuleID-ClientID',
  'GAME TYPE',
  'BRANDED',
  'JACKPOT',
  'FR',
  'max_paylines',
  'min_bet',
  'min_coin',
  'PLATFORM',
  'launch_type',
  'RELEASE DATE',
  'REL. DATE CRO',
  'REL. DATE NL',
  'CURACAO',
  'MGA',
  'DE',
  'NL',
  'RO',
  'SGA',
  'BE',
  'CRO',
  'BG',
  'CZ',
  'ESP',
  'SK',
  'GAME ICONS',
  'JJTW',
  'Game Icons',
  'PRODCOPY',
  'PRODUCTION',
  'ORYX GAME',
  'CODE',
  'TASK',
  'TASK NL',
  'notes',
  'Liinoo'
]

export const headerMappingCols = {
  GP: 'Game Provider',
  'RGS PROVIDER': 'RGS Provider',
  'GAME NAME': 'Game Name',
  'RGS code 1': 'RGS Code 1',
  'RGS code 2': 'RGS Code 2',
  'ModuleID-ClientID': 'Module ID - Client ID',
  'GAME TYPE': 'Game Type',
  BRANDED: 'Branded',
  JACKPOT: 'Jackpot',
  FR: 'Free Rounds',
  max_paylines: 'Max Paylines',
  min_bet: 'Min Bet',
  min_coin: 'Min Coin',
  PLATFORM: 'Platform',
  launch_type: 'Launch Type',
  'RELEASE DATE': 'Release Date',
  'REL. DATE CRO': 'Release Date CRO',
  'REL. DATE NL': 'Release Date NL',
  CURACAO: 'Curacao',
  MGA: 'MGA',
  DE: 'Germany',
  NL: 'Netherlands',
  RO: 'Romania',
  SGA: 'SGA',
  BE: 'Belgium',
  CRO: 'Croatia',
  BG: 'Bulgaria',
  CZ: 'Czech Republic',
  ESP: 'Spain',
  SK: 'Slovakia',
  'GAME ICONS': 'Game Icons',
  JJTW: 'JJTW',
  'Game Icons': 'Game Icons',
  PRODCOPY: 'Prod Copy',
  PRODUCTION: 'Production',
  'ORYX GAME': 'Oryx Game',
  CODE: 'Code',
  TASK: 'Task',
  'TASK NL': 'Task NL',
  notes: 'Notes',
  Liinoo: 'Liinoo'
}

export const alwaysExcludeHeaderCols = [
  'GP',
  'RGS PROVIDER',
  'BRANDED',
  'max_paylines',
  'REL. DATE CRO',
  'REL. DATE NL',
  'NL',
  'RO',
  'SGA',
  'CRO',
  'BG',
  'CZ',
  'ESP',
  'SK',
  'GAME ICONS',
  'PRODCOPY',
  'JJTW',
  'Game Icons',
  'PRODUCTION',
  'ORYX GAME',
  'CODE',
  'TASK',
  'TASK NL',
  'Liinoo'
]
